version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t dexels/dvdrental:$TAG .

      # deploy the image
      - run: docker push dexels/dvdrental:$TAG
