version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: |
          MINORTAG=1.0
          TAG=$MINORTAG.$CIRCLE_BUILD_NUM
          echo "Building tag: $TAG"
          docker build -t dexels/dvdrental:$TAG -t dexels/dvdrental:latest .
          docker push dexels/dvdrental:$TAG 
          docker push dexels/dvdrental:latest
